---
title: "week12"
author: "Patrick McGonagle"
date: "2026-04-20"
output: html_document
---

# Libraries 

```{r message = FALSE}
library(tidyverse)
library(tidytext)
library(tm)
library(jsonlite)
library(stm)
library(caret)
library(textclean)
library(textstem)
library(httr)
library(wordcloud)
# Didn't use qdap due to insane java troubleshooting, tried to accomplish the same without 
```

# Data Import and Cleaning 

```{r}
# USED AI - RedditExtractoR didn't allow me to pull the entire last year, ran into misc errors 

# all_posts <- list()
# next_page <- ""
# for (i in 1:10) { # Loop 
#   request <- GET(
#     url = "https://www.reddit.com/r/IOPsychology/new.json",
#     query = list(limit = 100, after = next_page),
#     add_headers(`User-agent` = "psy8712_task")
#   ) # Requests from URL 
#   content <- fromJSON(content(request, as = "text")) # Pulls the JSON from API
#   all_posts[[i]] <- content$data$children$data # getting content for for loop 
#   next_page <- content$data$after # Saying "go to next page"
#   if (is.null(next_page)) break #Break so it doens't run ad infintum 
# }
# week12_raw_tbl <- bind_rows(all_posts) |>
#   select(upvotes = ups, title) 
# saveRDS(week12_raw_tbl, "week12_tbl.rds") # Final data import 

# Commented out for loop after first run

# Tibble creation 
week12_tbl <- readRDS("week12_tbl.rds") |>
  as_tibble()

# Original corpus 
io_corpus_original <- VCorpus(VectorSource(week12_tbl$title))

# Remove IO terms using function (used AI regex)
remove_io_terms <- function(x) {
  gsub("i[\\/-]?o|industrial[\\s-]?organizational|psychology|psych", "", x, ignore.case = TRUE)
}

# Pre-processing 
io_corpus <- io_corpus_original |>
  tm_map(content_transformer(tolower)) |> # Everything lowercase 
  tm_map(content_transformer(remove_io_terms)) |> # Removing "IO" terms 
  tm_map(content_transformer(replace_contraction)) |> # getting rid of contradictions (i.e., "dont")
  tm_map(content_transformer(replace_symbol)) |> # Removing symbols like & and @
  tm_map(removePunctuation) |> # Getting rid of punctuation
  tm_map(removeNumbers) |> # Getting rid of numbers 
  tm_map(removeWords, stopwords("en")) |> # Removing stop words 
  tm_map(content_transformer(lemmatize_strings)) # lemmetizing 

# Spot checking shows steps were effective 

# Random row check function 
compare_them <- function(corp1, corp2) {
  idx <- 1:length(corp2) |> 
    sample(1) # Generate a random index 
  cat("Original Title:", corp1[[idx]]$content, "\n") # Print original 
  cat("Cleaned Title:", corp2[[idx]]$content, "\n") # print cleaned 
}

# Test
compare_them(io_corpus_original, io_corpus)

# Multiple checks show that this works

# Used tidy text in order to make sure the id's match (needed for joining)
io_tidy <- io_corpus |>
  tidy() |>
  select(doc_id = id, text = text)

# Unigrams and bigrams 
io_tokens <- bind_rows(
  io_tidy |> unnest_tokens(word, text, token = "words"), # Unigram 
  io_tidy |> unnest_tokens(word, text, token = "ngrams", n = 2) #bigram
) |>
  drop_na(word)

# Initial DTM
io_dtm <- io_tokens |>
  count(doc_id, word) |>
  cast_dtm(doc_id, word, n) # Makes sure its a dtm 

n_docs <- nrow(io_dtm) # 991 cases 

# Required k range 
k_min <- n_docs / 3
k_max <- n_docs / 2

# io_slim creation as per assigment 
io_slim_dtm <- removeSparseTerms(io_dtm, 0.9) # deletes any word missing from 98.5% of docs NOTE: didn't change much 
```

# Visualization 

```{r}
# Word cloud to check cleaning and viz these data
wordcloud(
  words = colnames(as.matrix(io_slim_dtm)), 
  freq = colSums(as.matrix(io_slim_dtm)), 
  max.words = 50
)

# Word cloud interpretation
## This word cloud shows that the pre-processing steps were successful, that is,
## words such as "IO" and "Psychology" are not present. Further, they show that 
## there are general topics like career advice (including grad school) and 
## technical skills. It also shows the prevalence of the biweekly discussions. 
```

# Analysis 

```{r}
# Seed for reproducibility 
set.seed(42)

# Create stm data for later steps 
io_stm_data <- tidy(io_slim_dtm) |>
  cast_sparse(document, term, count)

# LDA topic creation based on word cloud and spot checking 
lda_model <- stm(io_stm_data, K = 8, verbose = FALSE)


# Creation of topics tbl 
topics_tbl <- tidytext::tidy(lda_model, matrix = "theta") |>
  group_by(document) |> # Grouping by document to find most likely topic 
  slice_max(gamma, n = 1) |> # Finding highest gamma (probability)
  ungroup() |> 
  mutate(doc_id = as.numeric(document)) |> # Makes sure ids are numeric for join 
  inner_join(
    tibble(
      doc_id = 1:nrow(week12_tbl),
      original = week12_tbl$title,
      upvotes = week12_tbl$upvotes
    ), 
    by = "doc_id" # Rejoin to original tibble 
  ) |>
  mutate(
    topic = topic,
    probability = gamma,
    topic_label = case_when(
      topic == 1 ~ "Recurring Biweekly Discussions",
      topic == 2 ~ "Master's & Assessment Fieldwork",
      topic == 3 ~ "Job Search & Career Resources",
      topic == 4 ~ "Grad School & Market Entry",
      topic == 5 ~ "PhD, HR & Data Analysis",
      topic == 6 ~ "Internship Advice",
      topic == 7 ~ "Research, AI & Performance",
      topic == 8 ~ "People Analytics & Degree Transition"
    ) # Topics based on "labelTopics" highest prob and FREX
  ) |>
  drop_na(original) |> # Removes rows where text is missing
  select(doc_id, original, topic, topic_label, probability, upvotes) # Selects cols based on assignment 

# Topic selection questions: 
## 1: At first, based on the word cloud, I selected a lower K which
## unfortunately collapsed topics into non-comprehensible content areas. So, I 
## sequentially increased the k until the topics made more sense. The clearest
## indication that the topics were distinct enough was when bi-weekly
## discussions became their own topic and weren't a "general advice" topic. 
## Although, I'm sure there is a more rigorous way to choose topics here by
## testing fit using LDA, but this made the most sense to me. As mentioned above,
## I used the highest prob and FREX to make these judgement. 

## 2: Finally, when it came to the actual labels, I had some ideas about what to 
## label them, but the actual cleanest labels were difficult to ascertain. For 
## instance, I knew that bi-weekly discussions would be a topic, as with people
## analytics, but career advice was loaded onto many different topics so I 
## struggled with this. Finally, I checked my preliminary topic labels with
## Gemini and it gave quite clean labels. I know we discussed this as a human 
## reasoning task that has yet to be proven as AI-doable, but due to the vector 
## embeddings of language in LLMs, this is a task I felt it was well-suited for. 


# Machine Learning 
## decided on elastic net here due to the overwhelming number of predictors 

## Data prep for ml 
dtm_matrix <- as.matrix(io_slim_dtm) |> 
  as_tibble() |>
  mutate(doc_id = as.numeric(rownames(as.matrix(io_slim_dtm)))) # making the DTM into a matrix and then a tibble for caret to work with 

### Merging topics, token counts, upvotes
ml_data <- dtm_matrix |>
  inner_join(topics_tbl |> select(doc_id, topic, upvotes), by = "doc_id") |> # Join on doc_id
  select(-doc_id) |> # don't need after join  
  mutate(topic = as.factor(topic)) # making sure the topic is a factor 

### Holdout split 
train_index <- createDataPartition(ml_data$upvotes, p = 0.8, list = FALSE) # 80/20 split 
train_set <- ml_data[train_index, ]
test_set <- ml_data[-train_index, ]

## Model training 
train_control <- trainControl(method = "cv", number = 10) # 10-fold CV as required 

### Model 1: token only EN
model_tokens_en <- train(
  upvotes ~ . - topic, # gets rid of topic "-topic"
  data = train_set, 
  method = "glmnet", 
  trControl = train_control,
  tuneLength = 10 # 10 combinations of alpha and lambda 
)

### Model 2: Toeken and topics EN
model_combined_en <- train(
  upvotes ~ ., 
  data = train_set, 
  method = "glmnet", 
  trControl = train_control,
  tuneLength = 10
)
```